### ISSUE TITLE
Console.Write error (but not WriteLine)

### ISSUE THREAD

**Issue by thomaswp** [Orden4/WCSharp#2]
Hey, this is a really awesome library - thanks for making it.

I'm getting a weird error where when I use `Console.Write` I get a nil error on line 19514 of war3map.lua. This isn't the case with `Console.WriteLine`.

Now using `Write` was actually a mistake - of course I wanted it to print - but it took me ~30m to track down the error, and had thrown off some other bug tracing earlier. Would be great to see a fix.

**Comment by LordDamage175** [comment]
If you want to print any kind of Debugging message, just use the 
Util.Debug( ... )
command. It's part of the Shared package (or just Alt-Enter to add the appropriate "using" line).

It will accept any string, or Warcraft III object (e.g. Player, Unit) in which case it prints their handle ID.

You shouldn't really be writing anything to the console, as this code is going to be run by Warcraft III itself.

**Comment by Orden4** [comment]
The redirecting of the console output to `DisplayTextToPlayer` is not actually done by WCSharp. The `Util.Debug` method is actually somewhat of a remnant cause I wasn't even aware when I wrote it that `Console.WriteLine` redirected itself to this command.

I would assume that War3Api is in charge of this, though it may even just be CSharp.Lua redirecting it to the lua `print` function. I'd probably ask Drake53 in the hiveworkshop thread and then raise an issue at whichever repo is responsible.
