### ISSUE TITLE
Editor Objects Don't Show up in Constants.cs unless a string is changed

### ISSUE THREAD

**Issue by thomaswp** [Orden4/WCSharp#3]
You probably already know this, but since the Constants.cs generation works off of war3map.wts, which only contains strings from the editor, it will only detect custom objects that have a new string. If, for example, you don't change the name of a new, copied object (unit, item, etc.), it won't show up.

Fixing this would probably be pretty involved, but it would be good to have some documentation, e.g. in comments of Constants.cs to explain this. Took me 30m to figure it out!

**Comment by LordDamage175** [comment]
It's basically not possible to find anything if the string isn't different from the default.
You can also just add an editor suffix to the object, and it will be detected.

**Comment by Orden4** [comment]
Good suggestion! I'd still like to convert it into reading the binary data at some point so it could read unedited objects, but I'll see about at least a clearer warning for the current behaviour.

**Comment by Orden4** [comment]
I've added some details to the top of the auto generated file now for two common problems. https://github.com/Orden4/WCSharp/commit/53e7c9def3292c3f1dd030ff97ab196e240e42a7
