### ISSUE TITLE
Update CSharp.lua

### ISSUE THREAD

**Issue by thomaswp** [Orden4/WCSharp#4]
This is actually an issue for your fork of CSharp.lua, but I think issues are disabled there, so I'm posting here. Could you update it with the latest from `yanghuan/CSharp.lua:master`? It has a few bug fixes for issues I posted ([here](https://github.com/yanghuan/CSharp.lua/issues/388) and [here](https://github.com/yanghuan/CSharp.lua/issues/387)). It would be great to have those merged in with your WC3-specific transpiler. Thanks - I appreciate the help!

**Comment by Orden4** [comment]
Hello! Unfortunately, you are talking about War3Api, not WCSharp. WCSharp is just a set of libraries to make programming maps in C# easier, but the functionality of compiling the map, transpiling the code, etc. is handled by War3Api, which in turn is managed by Drake53. You'll want to open an issue on his [CSharp.lua repo](https://github.com/Drake53/CSharp.lua) for this.

EDIT: On the note of issues being disabled on the forks, I recommend opening a ticket on [War3Net](https://github.com/Drake53/War3Net) instead or just posting to the [C# mapmaking thread](https://www.hiveworkshop.com/threads/c-mapmaking-in-csharp.317839/), as Drake53 will typically respond pretty quickly. At least much faster than I am at responding to tickets anyway.
