### ISSUE TITLE
Multiple unit type event registry causing "key already exists" exception

### ISSUE THREAD

**Issue by YakaryBovine** [Orden4/WCSharp#6]
Hi, I'm using the prerelease version of WCSharp Events and I'm getting some key already exists exceptions when trying to register one function to a variety of unit types. I tried reproducing the issue cleanly but I'm a little confused by the results. Here's reproduction code:

```cs
private static void Start()
    {
      try
      {
        void TestFunction()
        {
          Console.WriteLine("1");
        }
        void TestFunction2()
        {
          Console.WriteLine("2");
        }
        PlayerUnitEvents.Register(UnitTypeEvent.Attacks, TestFunction, FourCC("hfoo"));
        PlayerUnitEvents.Register(UnitTypeEvent.Attacks, TestFunction2, FourCC("hfoo"));
        PlayerUnitEvents.Register(UnitTypeEvent.Attacks, TestFunction, FourCC("hkni"));
        PlayerUnitEvents.Register(UnitTypeEvent.Attacks, TestFunction2, FourCC("hkni"));
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex);
      }
    }
```
Running this produces the following exception: 
![image](https://user-images.githubusercontent.com/8995690/205446856-6de8f174-ceb6-49b5-8ee2-f1534f4caf22.png)

However, removing *any* of the event registrations causes the exception to go away, and that I don't understand.

**Comment by Orden4** [comment]
Sorry, some stuff came up for another project and I ended up totally forgetting to check this for a week. I have a guess already on this problem, but the test case is useful. I'll fix this tomorrow.

**Comment by YakaryBovine** [comment]
No problem! I'm just glad it's actually an issue with the library because I couldn't figure out the problem on my end. Thankyou.

**Comment by Orden4** [comment]
[Fixed in WCSharp.Events 2.1.0-rc12.](https://github.com/Orden4/WCSharp/commit/7ce525fa4183b3f107973fca0e66a8210db6bce7)

**Comment by YakaryBovine** [comment]
Just to confirm, this fixed both the test case and the issue I was having in my map. Cheers.
