### ISSUE TITLE
Comparing Point to null throws exception

### ISSUE THREAD

**Issue by YakaryBovine** [Orden4/WCSharp#8]
The following code will cause the following exception, when it should return `false`.
```cs
if (new Point(0, 0) == null) then
    {}
```
![image](https://user-images.githubusercontent.com/8995690/210560364-96070ec6-3397-4532-b5e4-01f09f68d2a2.png)

**Comment by Orden4** [comment]
Sorry again for the late response.
I actually ran into a similar issue fairly recently, should've checked if any of the WCSharp code was suffering from it... I'll get a proper fix soon(tm), but there's an easy solution of using `point is null` instead. It circumvents the operator overload of `==`.

I think I'll add my Discord tag to the readme so people can bug me on that (if I'm being slow), I'm just too horrid at checking my email lol.

**Comment by YakaryBovine** [comment]
That's a good work-around, cheers.
No worries, this is hardly urgent. Having a quicker way to contact you would be fantastic but I wouldn't have used it for this issue.

**Comment by Orden4** [comment]
Fixed in https://github.com/Orden4/WCSharp/commit/4d20ae49c6b923768407d63d0a9a7c4df13576c4
