### ISSUE TITLE
Doodad/Destructible Issue?

### ISSUE THREAD

**Issue by Nuyek** [Orden4/WCSharp#9]
Hey, just found this project and I'm loving it however I'm having a issue. I might just be dumb but I just copied the WCSharp template and make a map with a few crates. It seems like there's "two" crates on top of eachother after compile or a issue with the crate not registering the death the first time? I can attack it. It makes death animation then I have to attack it again to actually kill it.

If I try to hotkey kill multiple crates in a row it will only try to kill it once and then ignore the "second" crate.

Sorry if my explanation sucks here's a quick video: https://streamable.com/13r4jx

**Comment by YakaryBovine** [comment]
Hey @Scruffy8, this is probably an issue with War3Net, not WCSharp. Check out the issue I logged here: https://github.com/Drake53/War3Net/issues/39

**Comment by Orden4** [comment]
Indeed, this is an issue with War3Net, so you'll have to take this up with Drake53 who is responsible for that part. WCSharp is specifically only the namespaces that you import at the top of files like `using WCSharp.Events;` or whichever.
